JbNahan\Bundle\WorkflowManagerBundle\Entity\Node:
    type: entity
    table: node
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 255
        class:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: class
        configuration:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: configuration
    lifecycleCallbacks: {  }
    manyToOne:
        definition:
            targetEntity: Definition
            cascade: {  }
            mappedBy: null
            inversedBy: nodes
            joinColumns:
                workflow_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        states:
            targetEntity: ExecutionState
            mappedBy: node
    # manyToMany:
    #     outgoingNodes:
    #         targetEntity: Node
    #         mappedBy: incommingNodes
    #     incommingNodes:
    #         targetEntity: Node
    #         inversedBy: outgoingNodes
    #         joinTable:
    #             name: node_link
    #             joinColumns:
    #                 outgoing_node_id:
    #                     referencedColumnName: id
    #             inverseJoinColumns:
    #                 incoming_node_id:
    #                     referencedColumnName: id