services:
    jb_nahan.form.definition:
        class: JbNahan\Bundle\WorkflowManagerBundle\Form\DefinitionType
        arguments: ["@security.authorization_checker"]
        tags:
            - { name: form.type, alias: jb_nahan_definition }
    jb_nahan.form.execution_search:
        class: JbNahan\Bundle\WorkflowManagerBundle\Form\ExecutionSearchType
        arguments: ["@security.authorization_checker", "@jb_nahan.definition_manager"]
        tags:
            - { name: form.type, alias: jb_nahan_execution_search }