services:
    jb_nahan.form.defintion:
        class: JbNahan\Bundle\WorkflowManagerBundle\Form\DefinitionType
        arguments: ["@security.context"]
        tags:
            - { name: form.type, alias: jb_nahan_definition }