services:
    jb_nahan_workflow_manager.twig_extension:
        class: JbNahan\Bundle\WorkflowManagerBundle\Twig\Extension\JbNahanWmTwigExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }
