language: php

php:
  - 5.4

env:
  - MYSQL_VERSION=5.5

services: mysql

before_script:
  - composer self-update
  - composer install --prefer-dist -o
  - wget http://downloads.atoum.org/nightly/mageekguy.atoum.phar
  - phpenv --version
  - phpenv versions

script:
  - php vendor/atoum/atoum/bin/atoum -d "Tests/Units" "-bf" "vendor/autoload.php" "-c" "Tests/.atoum.php"