language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - MYSQL_VERSION=5.5

services: mysql

before_script:
  - composer self-update
  - composer install --prefer-dist -o
  - phpenv --version
  - phpenv versions