language: php

php:
  - 5.6
  - 7.0

services: mysql

before_script:
  - composer self-update
  - composer update
  - phpenv --version
  - phpenv versions

script:
  - php vendor/atoum/atoum/bin/atoum -d "Tests/Units" "-bf" "vendor/autoload.php" "-c" "Tests/.atoum.php"
