<?php

namespace JbNahan\Bundle\WorkflowManagerBundle\Repository;

use Doctrine\ORM\EntityRepository;

use InExtenso\Bundle\MgedBundle\Entity\GedTreeSearch;

/**
 * NodeConnectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NodeConnectionRepository extends EntityRepository
{
    /**
     * @param int $workflowId
     * @return ArrayCollection
     */
    public function getConnectionByWorkflowId($workflowId){
        $queryBuilder = $this->createQueryBuilder('r');
        $queryBuilder->leftJoin('JbNahan\Bundle\WorkflowManagerBundle\Entity\Node', 'n', \Doctrine\ORM\Query\Expr\Join::WITH, 'r.incomingNode = n.id')
                    ->where('n.workflow = :idwf')
                    ->setParameter('idwf', $workflowId)
                    ->orderBy('r.id');

        return $queryBuilder->getQuery()->getResult();
    }
}
